// vue-todo/src/app.vue
<template>
  <div id="app">
    <h1>TODO:</h1>
    <input id="todoInput" type="text" v-model="input">
    <button @click="_addTodo">Add</button>
    <ol>
      <li v-for="(todo, index) in todos" :key="index">{{ todo }}</li>
    </ol>
  </div>
</template>

<script>
export default {
  data() {
    return {
      todos: [],

      input: ""
    };
  },
  methods: {
    _addTodo(e) {
      this.todos.push(this.input);
      this.input = "";
    }
  }
};
</script>

<style>
#app {
  border: 1px solid green;
}
</style>

// react-todo/src/app.js
import React from "react";
import ReactDOM from "react-dom";

class TodoList extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			input: '',
			todos: []
		}

		this.onChange = (event) => {
			this.setState({ input: event.target.value });
		}

		this.onClick = (event) => {
			event.preventDefault()
			this.setState({
				input: '',
				todos: [...this.state.todos, this.state.input]
			});
		}
	}

	render() {
		return (
			<div style={{ border: '1px solid blue' }}>
				<h1>TODO:</h1>
				<input value={this.state.input} type="text" onChange={this.onChange}></input>
				<button onClick={this.onClick}>Add</button>
				<ol>
					{
						this.state.todos.map((item, index) => <li key={index}>{item}</li>)
					}
				</ol>
			</div>
		);
	}
}

Window.ReactTodo = (el) => {
	ReactDOM.render(<TodoList name="React" />, el);
}
